### PR TITLE
fix: update key usage error message to make it clear

### LINKED ISSUE #164: Key usage error message
### What is not working as expected?

> Error: certificate-chain is invalid, invalid self-signed certificate. Error: certificate with subject "CN=xx.com,O=Notary,L=xx,ST=CA,C=US": key usage must not have the bit positions for ContentCommitment, KeyEncipherment, DataEncipherment, KeyAgreement, CertSign, CRLSign, EncipherOnly, DecipherOnly set

If the certificate has more key usages than DigitalSignature, the error message will display all the other key usages. However, this can be confusing if the user didn't set those key usages.

### What did you expect to happen?

The error message should either state that there should be only one DigitalSignature key usage or mention the specific key usages that the certificate actually has and should not exist, instead of all of them.

### How can we reproduce it?

sign with a certificate that has unnecessary key usages

### Describe your environment

Linux

### What is the version of your notation-core-go Library?

v1.0.0

### PR DESCRIPTION
**Pull request by JeyJeyGao**
Resolves #164 
Signed-off-by: Junjie Gao <junjiegao@microsoft.com>

### CODE REVIEW

File: x509/cert_validations.go [hunk 1]
```diff
@@ -186,8 +176,34 @@ func validateLeafKeyUsage(cert *x509.Certificate) error {
...
+		invalidKeyUsages = append(invalidKeyUsages, "CRLSign")
+	}
+	if cert.KeyUsage&x509.KeyUsageEncipherOnly != 0 {
+		invalidKeyUsages = append(invalidKeyUsages, "EncipherOnly")
+	}
+	if cert.KeyUsage&x509.KeyUsageDecipherOnly != 0 {
+		invalidKeyUsages = append(invalidKeyUsages, "DecipherOnly")
+	}
+	if len(invalidKeyUsages) > 0 {
+		return fmt.Errorf("certificate with subject %q: key usage must not have the bit positions for %s set", cert.Subject, strings.Join(invalidKeyUsages, ", "))
```
Comment (Two-Hearts) [inline x509/cert_validations.go:206]: Can we make this error message more user friendly? The user might not fully understand what does `bit position` mean in key usage. Besides providing the error, we should provide information about what Notation is expecting. Something like:
```suggestion
		return fmt.Errorf("certificate with subject %q is invalid: key usage must be 'Digital Signature' only. Found %s", cert.Subject, strings.Join(invalidKeyUsages, ", "))
```

Comment (JeyJeyGao) [reply x509/cert_validations.go]: Updated.

File: x509/cert_validations.go [hunk 2]
```diff
@@ -186,8 +176,34 @@ func validateLeafKeyUsage(cert *x509.Certificate) error {
...
+		invalidKeyUsages = append(invalidKeyUsages, "CRLSign")
+	}
+	if cert.KeyUsage&x509.KeyUsageEncipherOnly != 0 {
+		invalidKeyUsages = append(invalidKeyUsages, "EncipherOnly")
+	}
+	if cert.KeyUsage&x509.KeyUsageDecipherOnly != 0 {
+		invalidKeyUsages = append(invalidKeyUsages, "DecipherOnly")
+	}
+	if len(invalidKeyUsages) > 0 {
+		return fmt.Errorf("certificate with subject %q is invalid: key usage must be 'Digital Signature' only, found %s", cert.Subject, strings.Join(invalidKeyUsages, ", "))
```
Comment (yizha1) [inline x509/cert_validations.go:206]:
```suggestion
		return fmt.Errorf("The certificate with subject %q is invalid. The key usage must be 'Digital Signature' only, but %s was found instead.", cert.Subject, strings.Join(invalidKeyUsages, ", "))
```

**Review by yizha1 — COMMENTED** [review]
Thanks @JeyJeyGao 

improve the error message a bit.

File: x509/cert_validations.go (hunk 2 above)
Comment (JeyJeyGao) [reply x509/cert_validations.go:206]: What about "The certificate with subject %q is invalid. The key usage must be \"Digital Signature\" only, but found %s"

Can we avoid using `was` because it is possible that there more than one items.

Comment (JeyJeyGao) [reply x509/cert_validations.go]: Updated.

**Review by Two-Hearts — DISMISSED** [review]
LGTM

File: x509/cert_validations.go [hunk 3]
```diff
@@ -184,10 +174,36 @@ func validateLeafKeyUsage(cert *x509.Certificate) error {
 		return err
 	}
 	if cert.KeyUsage&x509.KeyUsageDigitalSignature == 0 {
-		return fmt.Errorf("certificate with subject %q: key usage must have the bit positions for digital signature set", cert.Subject)
+		return fmt.Errorf("The certificate with subject %q is invalid. The key usage must have the bit positions for \"Digital Signature\"", cert.Subject)
```
Comment (shizhMSFT) [inline x509/cert_validations.go:177]: nit:
```suggestion
		return fmt.Errorf("The certificate with subject %q is invalid. The key usage must have the bit positions for \"Digital Signature\" set", cert.Subject)
```

File: x509/cert_validations.go [hunk 4]
```diff
@@ -184,10 +174,36 @@ func validateLeafKeyUsage(cert *x509.Certificate) error {
...
+	if cert.KeyUsage&x509.KeyUsageEncipherOnly != 0 {
+		invalidKeyUsages = append(invalidKeyUsages, "EncipherOnly")
+	}
+	if cert.KeyUsage&x509.KeyUsageDecipherOnly != 0 {
+		invalidKeyUsages = append(invalidKeyUsages, "DecipherOnly")
 	}
-	if cert.KeyUsage&kuLeafCertBlocked != 0 {
-		return fmt.Errorf("certificate with subject %q: key usage must not have the bit positions for %s set", cert.Subject, kuLeafCertBlockedString)
+	if len(invalidKeyUsages) > 0 {
+		return fmt.Errorf("The certificate with subject %q is invalid. The key usage must be \"Digital Signature\" only, but found %s", cert.Subject, strings.Join(invalidKeyUsages, ", "))
```
Comment (shizhMSFT) [inline x509/cert_validations.go:206]: `Digital Signature` is double quoted but strings in `invalidKeyUsages` are not.

File: x509/cert_validations.go (hunk 3 above)
Comment (Two-Hearts) [reply x509/cert_validations.go:177]: hmm, @shizhMSFT I guess we still need to display the current key usage of the invalid certificate?

Comment (Two-Hearts) [reply x509/cert_validations.go:177]: nvm, this is another error message.

File: x509/cert_validations.go (hunk 4 above)
Comment (JeyJeyGao) [reply x509/cert_validations.go:206]: Added quote for all key usage

File: x509/cert_validations.go (hunk 3 above)
Comment (JeyJeyGao) [reply x509/cert_validations.go]: Updated.

**Review by Two-Hearts — DISMISSED** [review]
LGTM

File: x509/cert_validations.go [hunk 5]
```diff
@@ -184,10 +174,36 @@ func validateLeafKeyUsage(cert *x509.Certificate) error {
 		return err
 	}
 	if cert.KeyUsage&x509.KeyUsageDigitalSignature == 0 {
-		return fmt.Errorf("certificate with subject %q: key usage must have the bit positions for digital signature set", cert.Subject)
+		return fmt.Errorf("The certificate with subject %q is invalid. The key usage must have the bit positions for \"Digital Signature\" set", cert.Subject)
+	}
+
+	var invalidKeyUsages []string
+	if cert.KeyUsage&x509.KeyUsageContentCommitment != 0 {
+		invalidKeyUsages = append(invalidKeyUsages, "\"ContentCommitment\"")
```
Comment (shizhMSFT) [inline x509/cert_validations.go:182]: nit:
```suggestion
		invalidKeyUsages = append(invalidKeyUsages, `"ContentCommitment"`)
```

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by Two-Hearts — APPROVED** [review]
LGTM

**Review by shizhMSFT — APPROVED** [review]
LGTM

**Review by priteshbandi — APPROVED** [review]
LGTM

File: x509/cert_validations.go [hunk 6]
```diff
@@ -184,10 +174,36 @@ func validateLeafKeyUsage(cert *x509.Certificate) error {
 		return err
 	}
 	if cert.KeyUsage&x509.KeyUsageDigitalSignature == 0 {
-		return fmt.Errorf("certificate with subject %q: key usage must have the bit positions for digital signature set", cert.Subject)
+		return fmt.Errorf("The certificate with subject %q is invalid. The key usage must have the bit positions for \"Digital Signature\" set", cert.Subject)
+	}
+
+	var invalidKeyUsages []string
+	if cert.KeyUsage&x509.KeyUsageContentCommitment != 0 {
+		invalidKeyUsages = append(invalidKeyUsages, `"ContentCommitment"`)
```
[the remark this answers is not in the document]
Comment (JeyJeyGao) [reply x509/cert_validations.go:182]: Yes, but if we don't add the quotes here, we'll need a for loop to add quotes for each key's usage. It's a trade-off.

[the remark this answers is not in the document]
Comment (JeyJeyGao) [reply x509/cert_validations.go:182]: Alternatively, we can add it in the join, but it might make the code a bit harder to read.
