### PR TITLE
fix: fix `signerInfo.authenticSigningTime` according to spec

### LINKED ISSUE #38: Support AuthenticSigningTime in SignerInfo
Currently, [`SignerInfo`](https://github.com/notaryproject/notation-core-go/blob/main/signer/signer.go#L32) does not support differentiating SigningTime (incase of `notary.x509`) from AuthenticSigningTime (incase of `notary.signingAuthority.x509`)

### PR DESCRIPTION
**Pull request by Two-Hearts**
This PR fixes `signerInfo.AuthenticSigningTime` to return the correct results. 

According to spec: https://github.com/notaryproject/specifications/blob/main/specs/signature-specification.md#signing-time--authentic-signing-time: 
`authentic signing time` is a valid concept only under signing scheme [`notary.x509.signingAuthority`](https://github.com/notaryproject/specifications/blob/main/specs/signing-scheme.md/#notaryx509signingauthority). Therefore, for other signing schemes, this function should return an error.

Resolves #38

### CODE REVIEW

File: signature/types.go [hunk 1]
```diff
@@ -197,17 +198,20 @@ func (signerInfo *SignerInfo) ExtendedAttribute(key string) (Attribute, error) {
 	return Attribute{}, errors.New("key not in ExtendedAttributes")
 }
 
-// AuthenticSigningTime returns the authentic signing time
+// AuthenticSigningTime returns the authentic signing time under signing scheme
+// notary.x509.signingAuthority.
+// For signing scheme notary.x509, since it only supports authentic timestamp,
+// an error is returned.
+//
+// Reference: https://github.com/notaryproject/specifications/blob/main/specs/signature-specification.md#signing-time--authentic-signing-time
```
Comment (shizhMSFT) [inline signature/types.go:206]: Instead of referencing the `main` branch, can you reference a permanent link?

File: signature/types.go [hunk 2]
```diff
@@ -197,17 +198,20 @@ func (signerInfo *SignerInfo) ExtendedAttribute(key string) (Attribute, error) {
...
-	switch signerInfo.SignedAttributes.SigningScheme {
-	case SigningSchemeX509SigningAuthority:
-		return signerInfo.SignedAttributes.SigningTime, nil
-	case SigningSchemeX509:
-		if len(signerInfo.UnsignedAttributes.TimestampSignature) > 0 {
-			// TODO: Add TSA support for AutheticSigningTime
-			// https://github.com/notaryproject/notation-core-go/issues/38
-			return time.Time{}, errors.New("TSA checking has not been implemented")
+	switch signingScheme := signerInfo.SignedAttributes.SigningScheme; {
+	case signingScheme == SigningSchemeX509SigningAuthority:
```
Comment (shizhMSFT) [inline signature/types.go:209]:
```suggestion
	case SigningSchemeX509SigningAuthority:
```

File: signature/types.go [hunk 3]
```diff
@@ -197,17 +198,20 @@ func (signerInfo *SignerInfo) ExtendedAttribute(key string) (Attribute, error) {
...
+		if signerInfo.SignedAttributes.SigningTime.IsZero() {
+			return time.Time{}, fmt.Errorf("authentic signing time must be present under signing scheme %q", signingScheme)
 		}
+		return signerInfo.SignedAttributes.SigningTime, nil
```
Comment (shizhMSFT) [inline signature/types.go:213]: nit: code style: readability: consider
```suggestion
		signingTime := signerInfo.SignedAttributes.SigningTime {
		if signingTime.IsZero() {
			return time.Time{}, fmt.Errorf("authentic signing time must be present under signing scheme %q", signingScheme)
		}
		return signingTime, nil
```

**Review by shizhMSFT — APPROVED** [review]
LGTM

File: signature/types.go [hunk 4]
```diff
@@ -197,17 +198,21 @@ func (signerInfo *SignerInfo) ExtendedAttribute(key string) (Attribute, error) {
...
 	case SigningSchemeX509SigningAuthority:
-		return signerInfo.SignedAttributes.SigningTime, nil
-	case SigningSchemeX509:
-		if len(signerInfo.UnsignedAttributes.TimestampSignature) > 0 {
-			// TODO: Add TSA support for AutheticSigningTime
-			// https://github.com/notaryproject/notation-core-go/issues/38
-			return time.Time{}, errors.New("TSA checking has not been implemented")
+		signingTime := signerInfo.SignedAttributes.SigningTime
+		if signingTime.IsZero() {
+			return time.Time{}, fmt.Errorf("authentic signing time must be present under signing scheme %q", signingScheme)
```
Comment (priteshbandi) [inline signature/types.go:212]: Is it must under the spec or its optional? AFAIR the previous version of spec said that authentic signing time can be used only under `SigningSchemeX509SigningAuthority` but it was optional

Comment (Two-Hearts) [reply signature/types.go:212]: @priteshbandi Yes, it's a `REQUIRED` field according to the spec: https://github.com/notaryproject/specifications/blob/main/specs/signature-specification.md#standard-attributes

One thing to point out is that, we are still using the `SigningTime` field under `SigningSchemeX509SigningAuthority` as authentic signing time. However, based on spec, we should use the `Authentic Signing Time` field instead. (both fields are `REQUIRED`)

**Review by priteshbandi — APPROVED** [review]
LGTM

**Review by JeyJeyGao — APPROVED** [review]
LGTM
